name: connect-publish
on:
  push:
    branches:
      - master

jobs:
  connect-publish:
    name: connect-publish
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://rsc.soleng.rstudioservices.com/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: all
          dir: |
            ./API/:bike_predict_api
            ./App/client_app:bike_predict_app
            ./App/model_performance:bike_predict_model_performance
            ./Email/:bike_predict_email
            ./ETL/clean_raw/:bike_predict_clean_raw
            ./ETL/intake_raw/:bike_predict_intake_raw
            ./ETL/station_api_to_pin/:bike_predict_pin_stations
            ./Model/build_rxgb/:bike_predict_build_xgb
            ./Model/model_quality_metrics/:bike_predict_model_quality

